### ISSUE TITLE
Unhandled Rejection (Error) The 'navigation' object hasn't been initialized yet

### ISSUE THREAD

**Issue by drewweaver27** [HitPauseApp/HitPause#26]
# Bug Report 

## App Breaking? (Causes crashes, screens full of red text, etc.) Yes/No
Sort of

## Frequency (Only on Expo Start / Every reload of the app / every couple reloads / randomly) 
Every couple of reloads

### Describe Bug
This error will come up on the occasional refresh of the app when already signed in and auto-navigating to the homescreen. Another manual refresh will usually make it go away

#### Did this happen after you installed/modified a package? If so, which one. 
Don't believe so

### Supporting Images, Code Blocks, Etc. 
![image](https://user-images.githubusercontent.com/24489555/95385656-489c2a80-08bc-11eb-8d95-70c04d7f4eaa.png)
![image](https://user-images.githubusercontent.com/24489555/95385927-a2045980-08bc-11eb-953d-2886c1d6d7c5.png)
![image](https://user-images.githubusercontent.com/24489555/95385891-931da700-08bc-11eb-9802-d7695498fa0c.png)

**Comment by tannerstern** [comment]
We will need to monitor this, but the changes in [this routing fix](https://github.com/HitPauseApp/HitPause/commit/f26c7622483708ac70f47e3e7348780ad69811c8) should bring an end to this issue.

**Comment by drewweaver27** [comment]
@tannerstern  Do you think this could be related to #31? When running on the Android Simulator from the published app page, I can get to the login screen, type my creds and then I get a crash when trying to log in.

**Comment by tannerstern** [comment]
I have not seen this error crop up at all recently. I think our nav changes fixed it, so I'm closing it for now.
