### ISSUE TITLE
HistoryScreen - TypeError: Can't convert null to object

### ISSUE THREAD

**Issue by drewweaver27** [HitPauseApp/HitPause#56]
# Bug Report 

## App Breaking? (Causes crashes, screens full of red text, etc.) Yes/No

Yes

## Frequency (Only on Expo Start / Every reload of the app / every couple reloads / randomly) 

Always when navigating to the history screen page

### Describe Bug

When clicking on history page from the navigator, it goes to the history screen page, waits for a second, and then throws this error after making the database query. I assume this can just be fixed by adding an if statement to check if the user has any history or if it is null (in my case, I have no history so I get null in return).

#### Did this happen after you installed/modified a package? If so, which one. 

No

### Supporting Images, Code Blocks, Etc. 
![image](https://user-images.githubusercontent.com/24489555/98000195-3d082a80-1dba-11eb-85e7-39435aaa1434.png)
![image](https://user-images.githubusercontent.com/24489555/98000215-45f8fc00-1dba-11eb-9fd0-7e806f6ea73e.png)

**Comment by drewweaver27** [comment]
Hey @tannerstern I think this was from one of your stories, want to double check this?

**Comment by tannerstern** [comment]
Yeah, when no user history existed, there were some problems with null. #58 should fix this, specifically 8c7e627485472f5c98aac45f486462fd4aaf7a4c.
