### ISSUE TITLE
Warning: Can't perform a React state update on an unmounted component

### ISSUE THREAD

**Issue by tannerstern** [HitPauseApp/HitPause#61]
# Bug Report 

## App Breaking? (Causes crashes, screens full of red text, etc.) Yes/No
No

## Frequency (Only on Expo Start / Every reload of the app / every couple reloads / randomly) 
Every couple reloads

### Describe Bug
Sometimes this error (called a warning in the console but appears in red) appears when the app is loaded. I expect it comes from state being used in the `initialRouteName` property of the navigation components in `App.js`, though I'm not sure of this or how to fix it if it is.

#### Did this happen after you installed/modified a package? If so, which one. 
No

### Supporting Images, Code Blocks, Etc. 
![image](https://user-images.githubusercontent.com/43083093/98063568-56db5900-1e1e-11eb-9320-562523f6d07f.png)

**Comment by drewweaver27** [comment]
@tannerstern Does this come up on a certain page or just when the app loads up?

**Comment by tannerstern** [comment]
@drewweaver27 I think it comes up right after you log in (go to the homepage for the first time)

**Comment by drewweaver27** [comment]
@tannerstern  Hmm I went to try to get this to reproduce and I couldn't seem to get it to come up. I have seen one of these warnings come up but I don't remember what the context was.

**Comment by drewweaver27** [comment]
@tannerstern I think this bug has worked its way out with updates to App.js in recent sprints. Safe to close?

**Comment by tannerstern** [comment]
@drewweaver27 yes, probably safe to close.
