### ISSUE TITLE
Warning: componentWillReceiveProps has been renamed, and is not recommended for use

### ISSUE THREAD

**Issue by tannerstern** [HitPauseApp/HitPause#86]
# Bug Report 

## App Breaking? (Causes crashes, screens full of red text, etc.) Yes/No
No, this is not currently an app-breaking bug

## Frequency (Only on Expo Start / Every reload of the app / every couple reloads / randomly) 
Every app reload

### Describe Bug
When the home screen loads, a warning appears (pictured below). It appears this "componentWillReceiveProps" warning originates from TouchableOpacity and is fixed in a newer version of React Native. [This GitHub thread](https://github.com/react-native-modal/react-native-modal/issues/299) gives more information.

#### Did this happen after you installed/modified a package? If so, which one.
No

### Supporting Images, Code Blocks, Etc. 
![image](https://user-images.githubusercontent.com/43083093/105854015-50d7bd00-5fb4-11eb-8dc1-32bcc1cc6f90.png)

**Comment by tannerstern** [comment]
@drewweaver27 This has something to do with the version of react-native / expo we built our project on. It is a warning only, and as we have no intention of updating our base versions any time soon, we might as well close this issue, right?

**Comment by drewweaver27** [comment]
@tannerstern Yes that would be correct, I think we can close
